export const PKEY = {
  TOKEN: 'token',

  PRIVIGELES: 'privileges',
  DEBUG: 'debug',

  MENU: 'menu',

  PERMISOS_LIST : "PERMISOS_LIST",
  PERMISOS_USER : "PERMISOS_USER",
  USUARIO_LOGEAD: "USUARIO_LOGEAD",
  LOCAL_LOGEADO: "LOCAL_LOGEADO",
  MONEDA: "MONEDA",
};

